// <auto-generated />
using System;
using BeerWorkshop.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeerWorkshop.Database.Migrations;

[DbContext(typeof(BeerWorkshopContext))]
[Migration("20251109104156_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Devices.DeletedDevicesStatistic", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("Quantity")
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("TEXT");

                b.Property<int>("TransactionType")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("DeletedDevicesStatistics");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Devices.Device", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Devices");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Devices.DevicesInventory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("DeviceId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("IncomingDate")
                    .HasColumnType("TEXT");

                b.Property<decimal>("PurchasePrice")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Quantity")
                    .HasColumnType("TEXT");

                b.Property<decimal>("RetailPrice")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("DeviceId");

                b.ToTable("DevicesInventory");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Devices.DevicesStatistic", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("DeviceId")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Quantity")
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("TEXT");

                b.Property<int>("TransactionType")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("DeviceId");

                b.ToTable("DevicesStatistic");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.DeletedProductsStatistic", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("ProductName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("Quantity")
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("TEXT");

                b.Property<int>("TransactionType")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("DeletedProductsStatistics");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("ProductType")
                    .HasColumnType("INTEGER");

                b.Property<int>("UnitOfMeasure")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Products");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.ProductsInventory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<int>("ExpirationMeasure")
                    .HasColumnType("INTEGER");

                b.Property<int>("ExpirationTime")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("IncomingDate")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("ManufactureDate")
                    .HasColumnType("TEXT");

                b.Property<Guid>("ProductId")
                    .HasColumnType("TEXT");

                b.Property<decimal>("PurchasePrice")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Quantity")
                    .HasColumnType("TEXT");

                b.Property<decimal>("RetailPrice")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.ToTable("ProductsInventory");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.ProductsStatistic", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ProductId")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Quantity")
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("TEXT");

                b.Property<int>("TransactionType")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.ToTable("ProductsStatistic");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Devices.DevicesInventory", b =>
            {
                b.HasOne("BeerWorkshop.Database.Entities.Devices.Device", "Device")
                    .WithMany()
                    .HasForeignKey("DeviceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Device");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Devices.DevicesStatistic", b =>
            {
                b.HasOne("BeerWorkshop.Database.Entities.Devices.Device", "Device")
                    .WithMany()
                    .HasForeignKey("DeviceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Device");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.ProductsInventory", b =>
            {
                b.HasOne("BeerWorkshop.Database.Entities.Products.Product", "Product")
                    .WithMany("Inventory")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.ProductsStatistic", b =>
            {
                b.HasOne("BeerWorkshop.Database.Entities.Products.Product", "Product")
                    .WithMany("Statistics")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

        modelBuilder.Entity("BeerWorkshop.Database.Entities.Products.Product", b =>
            {
                b.Navigation("Inventory");

                b.Navigation("Statistics");
            });
#pragma warning restore 612, 618
    }
}
